export const InvalidWorkspaceErrorMessage = "No workspace open for Code Index"
export const CodeContextStartMessage = "(HAI) Adding Code Context"
export const CodeContextCompletionMessage = "Code Context Addition Done, Moving Ahead with Code Indexing..."
export const CodeIndexStartMessage = "(HAI) Indexing Code"
export const CodeIndexCompletionMessage = "Indexing Code Completed"
export const CodeContextErrorMessage = "Error occurred while adding Code Context. Please restoring the current workspace."
